# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
  frontend:
    image: antoniopapa1991/frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: mina
      MYSQL_PASSWORD: au4a83
      MYSQL_ROOT_PASSWORD: au4a83

    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306


